### ISSUE TITLE
Remove unused rxjs imports

### ISSUE THREAD

**Issue by cgatian** [BrycePearce/WhenDoesItAir#2]
https://github.com/BrycePearce/WhenDoesItAir/blob/80e3f0837fb585a4ea0ebfa7260660ec2c3c479c/client/src/app/services/title.service.ts#L3-L6

**Comment by BrycePearce** [comment]
https://github.com/BrycePearce/WhenDoesItAir/commit/6204e628a8b4574252483a5733f0ac49897181c6

done

**Comment by cgatian** [comment]
You're killing it!
